- name: Docker install
  hosts: localhost
  become: yes
  tasks: 
  - name: Install Prepare
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release 
      state: latest 
      update_cache: yes   

  - name: Add Docker Key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/debian bullseye stable
      state: present

  - name: Install Docker 
    apt:
      name: docker-ce
      state: latest
      update_cache: true