route:
  group_by: [Alertname] 
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: nairands@gmail.com  
    from: nairands@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "nairands@gmail.com"
    auth_identity: "nairands@gmail.com"
    auth_password: "*******"