INDEX_PATH = "$PWD/B11Workshop/ProjectWork/index.html"

node {
    stage('CloneRepo') { 
        git 'https://github.com/Niardan/DevOps.git'
    }
	    try {
         stage('Build Nginx') {
                  sh "docker run --name some-nginx -v INDEX_PATH:/usr/share/nginx/html:ro -p 9889:80 -d nginx"
             }
         stage('Check File') {
                  sh "curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:9889"
             }
  }
}
